# Generated by Django 4.1.3 on 2022-12-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ip',
            new_name='session_hash',
        ),
        migrations.AlterField(
            model_name='user',
            name='temporary_questions',
            field=models.CharField(default='0|0', max_length=50),
        ),
    ]
