# Generated by Django 4.1.3 on 2022-12-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_ip_user_session_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_hash',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
